In [1]:
! pip install numpy

In [2]:
import numpy as np

In [4]:
k = [1,2,3,4,46]
a1 = np.array(k)
print(a1)

[ 1  2  3  4 46]


In [5]:
a2 = np.array([1,45,78,"python",26.58,89])
a2

array(['1', '45', '78', 'python', '26.58', '89'], dtype='<U11')

In [6]:
a1.dtype

dtype('int32')

In [7]:
a2.dtype

dtype('<U11')

In [8]:
a1 = np.append(a1,67)
a1

array([ 1,  2,  3,  4, 46, 67])

In [9]:
a2 = np.append(a2,[3,78,34])
a2

array(['1', '45', '78', 'python', '26.58', '89', '3', '78', '34'],
      dtype='<U11')

In [10]:
b = np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
c = np.linspace(1,10,20)
c

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [12]:
d = np.logspace(1,10,20)
d

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [13]:
np.full(10,"numpy")

array(['numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy', 'numpy',
       'numpy', 'numpy', 'numpy'], dtype='<U5')

In [14]:
np.full(5,"1 2")

array(['1 2', '1 2', '1 2', '1 2', '1 2'], dtype='<U3')

In [15]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10,dtype = int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros(4)

array([0., 0., 0., 0.])

In [19]:
np.eye(2,2)

array([[1., 0.],
       [0., 1.]])

In [20]:
a3  = np.array([[1,2,3],[4,5,6],[7,8,9]])
a3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a3.ndim
a3.size
a3.shape
a3.dtype
a3.itemsize
a3.nbytes

36

In [27]:
len(a3)

3

In [28]:
a4 = np.array([
    [[1,2,3,4],[5,6,7,8]],
               [[9,10,11,12],
                [13,14,15,16]]
              ])
a4

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [32]:
a = np.array([1,2,3,4,5],ndmin=15)
a

array([[[[[[[[[[[[[[[1, 2, 3, 4, 5]]]]]]]]]]]]]]])

In [33]:
a.ndim

15