In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
a[0]

1

In [4]:
a[-1]

5

In [5]:
a[1:4]

array([2, 3, 4])

In [6]:
a[2:]

array([3, 4, 5])

In [7]:
a[-3:]

array([3, 4, 5])

In [8]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
b[0][2]

3

In [11]:
b[0,2]

3

In [12]:
b[:,-1]

array([4, 8])

In [15]:
b[:,-1]

array([4, 8])

In [16]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

In [17]:
b[1:3,1:3] 

array([[6, 7]])

In [20]:
# 2,4,6,8
b[:,1::2]

array([[2, 4],
       [6, 8]])

In [22]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [29]:
# 2,8,14,10
c[[0,0,1,1],[0,1,1,0],[1,3,1,1]]

array([ 2,  8, 14, 10])

In [25]:
c[0][1][1:3]

array([6, 7])

In [27]:
c[1][0][-2:]

array([11, 12])

In [28]:
c[[1,1],[0,0],[2,3]] # c(1,0,2)(1,0,3)

array([11, 12])

In [30]:
d = np.arange(1,21)

In [31]:
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [32]:
d = d.reshape(4,5)
d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
d.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [34]:
d.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [35]:
d.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [36]:
d.reshape(-1,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [37]:
f = np.arange(1,51).reshape(5,5,2)
f

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36],
        [37, 38],
        [39, 40]],

       [[41, 42],
        [43, 44],
        [45, 46],
        [47, 48],
        [49, 50]]])

In [38]:
a

array([1, 2, 3, 4, 5])

In [39]:
for i in a:
    print(i)

1
2
3
4
5


In [40]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [43]:
for i in b:      # i holds rows
    for j in i:  # j holds row elements
        print(j,end = " ")

1 2 3 4 5 6 7 8 

In [44]:
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [45]:
for i in c:            # i holds 2-d array
    for j in i:        # j holds rows
        for k in j:    # k holds element
            print(k)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [46]:
for i in np.nditer(c):
    print(i,end = " ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [47]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [48]:
g = np.array([[9,10,11,12],[13,14,15,16]])
g

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [49]:
np.concatenate((b,g))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
np.min(g)

9

In [51]:
np.max(g)

16

In [52]:
np.argmin(c)

0

In [53]:
np.argmax(c)

15

In [63]:
c.mean()
np.median(c)
np.var(c)
np.average(c)
np.std(c)
np.corrcoef(a)
np.sum(c)
np.sum(c,1) # sum of the row elements 
np.sum(c,0)

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [64]:
np.hstack(c)

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [65]:
np.vstack((b,g))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [66]:
np.hstack((b,g))

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [67]:
np.c_[b,g]

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])

In [68]:
np.r_[b,g]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [70]:
np.row_stack((b,g)) # r_,vstack

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
np.column_stack((b,g)) # c_,hstack

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])