In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([[1,2,3,4],[5,6,7,8]])
c = np.array([[[1,2,3,4,5]],[[6,7,8,9,10]]])

In [5]:
np.sqrt(a)
np.exp(a)
np.sin(c)
np.cos(c)
np.tan(c)

array([[[ 1.55740772, -2.18503986, -0.14254654,  1.15782128,
         -3.38051501]],

       [[-0.29100619,  0.87144798, -6.79971146, -0.45231566,
          0.64836083]]])

In [8]:
np.log(a)
np.log2(c)
np.log10(b)
np.diff(c)

array([[[1, 1, 1, 1]],

       [[1, 1, 1, 1]]])

In [9]:
np.add(a,4)

array([5, 6, 7, 8, 9])

In [10]:
a1 = np.array([2,4,6,8,9])
np.add(a,a1)

array([ 3,  6,  9, 12, 14])

In [11]:
np.multiply(b,3)
np.mod(c,3)
np.subtract(c,3)
np.divide(b,2)

array([[0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. ]])

In [15]:
np.power(c,2)
np.remainder(c,3)
np.degrees(b)

array([[ 57.29577951, 114.59155903, 171.88733854, 229.18311805],
       [286.47889757, 343.77467708, 401.07045659, 458.3662361 ]])

In [14]:
np.reciprocal(c,dtype = float)

array([[[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ]],

       [[0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ]]])

In [18]:
np.diff(c)

array([[[1, 1, 1, 1]],

       [[1, 1, 1, 1]]])

In [17]:
a

array([1, 2, 3, 4, 5])

In [19]:
np.ediff1d(c) # converts the array into 1-d and calculates the consecutive difference of each element

array([1, 1, 1, 1, 1, 1, 1, 1, 1])

In [20]:
np.i0(c) # bessel function

array([[   1,    2,    4,   11,   27],
       [  67,  168,  427, 1093, 2815]])

In [21]:
im = np.array([1+2j,4+7j,12+87j])
im

array([ 1. +2.j,  4. +7.j, 12.+87.j])

In [22]:
np.real(im)

array([ 1.,  4., 12.])

In [23]:
np.imag(im)

array([ 2.,  7., 87.])

In [24]:
original = np.arange(1,10)
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
copy = original.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
copy[0] = 56
copy

array([56,  2,  3,  4,  5,  6,  7,  8,  9])

In [27]:
original

array([56,  2,  3,  4,  5,  6,  7,  8,  9])

In [28]:
copy1 = original.flatten()
copy1

array([56,  2,  3,  4,  5,  6,  7,  8,  9])

In [29]:
copy1[5] = 100
copy1

array([ 56,   2,   3,   4,   5, 100,   7,   8,   9])

In [30]:
original

array([56,  2,  3,  4,  5,  6,  7,  8,  9])

In [33]:
np.random.randint(100,size = (20))

array([49, 46, 10, 40, 12, 96, 13, 34, 86, 68, 16,  7, 37, 39, 23, 57, 50,
       49, 25, 50])

In [34]:
np.random.randint(1,50,size = (3,4))

array([[ 9, 15, 10,  3],
       [36, 19, 26, 13],
       [20,  9,  9, 15]])

In [35]:
np.random.rand(45)

array([0.5572007 , 0.90806568, 0.04442555, 0.85727522, 0.11153013,
       0.26519299, 0.57903291, 0.43407734, 0.33963662, 0.42014935,
       0.38637448, 0.27509065, 0.24602708, 0.11035955, 0.40184856,
       0.51526482, 0.60952791, 0.88734706, 0.16406824, 0.14900312,
       0.64853742, 0.94808178, 0.20007891, 0.92709939, 0.35033345,
       0.83467312, 0.68035585, 0.99889082, 0.44708932, 0.80933636,
       0.4310383 , 0.61012345, 0.02236395, 0.5801803 , 0.5264887 ,
       0.91065354, 0.96925126, 0.06557127, 0.85564284, 0.26461652,
       0.13635958, 0.5808281 , 0.06334696, 0.2322989 , 0.26011129])

In [36]:
np.random.choice([1,2,3,45,67,89,36,71,70],size = (4,5))

array([[70, 89, 67,  1, 36],
       [ 1, 89, 89, 71, 89],
       [70, 70,  3, 89, 89],
       [ 3, 71,  3, 71, 45]])

In [37]:
c

array([[[ 1,  2,  3,  4,  5]],

       [[ 6,  7,  8,  9, 10]]])

In [38]:
np.random.shuffle(c)

In [39]:
c

array([[[ 6,  7,  8,  9, 10]],

       [[ 1,  2,  3,  4,  5]]])

In [40]:
np.random.randn(10)

array([ 0.34169331,  0.26303029,  0.97995769,  0.7867985 ,  0.54481405,
        1.18667456,  0.73787691, -1.29005702,  0.7011627 ,  1.66911225])

In [42]:
np.random.normal(c)

array([[[ 5.69812341,  8.41757382,  6.9992187 , 10.55986622,
          7.68127908]],

       [[ 2.02486705,  1.88377087,  1.93881148,  3.62137643,
          5.19925727]]])

In [44]:
np.random.binomial(10,p = [0.1],size = (4))

array([1, 3, 2, 1])

In [45]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
h = []
for i in a:
    if i>4:
        h.append(True)
    else: 
        h.append(False)
c = a[h]
c

array([5])

In [49]:
k = b>4
e = b[k]
e

array([5, 6, 7, 8])

In [51]:
c

array([5])

In [52]:
g = np.arange(1,21).reshape(4,5)
g

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [54]:
g.transpose()

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [55]:
g.T

array([[ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19],
       [ 5, 10, 15, 20]])

In [57]:
a1

array([2, 4, 6, 8, 9])

In [58]:
np.dot(a,a1)

105

In [59]:
np.dot(a,b)

ValueError: shapes (5,) and (2,4) not aligned: 5 (dim 0) != 2 (dim 0)